#version 410 core

in vec3 normal;
in vec3 color;
out vec4 fragmentColor;
in vec3 fragPos;

uniform float ambientStrength = 0.3f;
uniform vec4 ambientColor = vec4(1, 1, 1, 0);

uniform float lightStrength = 0.7;

struct DirectionalLight
{
    vec3 color;
    float ambientIntensity;
    vec3 direction;
    float diffuseIntensity;
};

uniform DirectionalLight directionalLight;

uniform vec3 viewPos; // The position of the camera
uniform float specularStrength = 0.1f;

void main() {
    // Ambient
    vec3 ambient = directionalLight.color * directionalLight.ambientIntensity;

    // Diffuse
    float diffuseFactor = max(dot(normalize(normal), normalize(directionalLight.direction)),0.0f);
    vec3 diffuse = directionalLight.color * directionalLight.diffuseIntensity * diffuseFactor;

    // Specular

    vec3 viewDir = normalize(viewPos - fragPos);
    vec3 reflectDir = reflect(-directionalLight.direction, normal);

    // The last parameter here is important. The higher the power we raise this to...
    // ... the smaller the effect of the specular light.
    // The "light orb" generated by the specular light will be smaller, but brighter.
    // The smaller the power raised, the bigger, but also dimmer, this "light orb" will be.
    float spec = pow(max(dot(viewDir, reflectDir), 0.0), 16);
    vec3 specular = specularStrength * spec * directionalLight.color;

    vec3 phong = (ambient + diffuse) * color + specular;

    fragmentColor = vec4(phong, 1.0f);   //color given to current fragment (pixel)
}
